import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useGetLanguagePreference, useSetLanguagePreference } from '../hooks/useQueries';
import { useInternetIdentity } from '../hooks/useInternetIdentity';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // App
    'app.subtitle': 'Audit Management',
    
    // Landing Page
    'landing.hero.badge': 'Professional Audit Management',
    'landing.hero.title': 'Streamline Your Audit Engagements',
    'landing.hero.subtitle': 'A comprehensive platform for managing audit organizations, entities, engagements, and data with advanced analytics and secure document handling.',
    'landing.hero.cta_primary': 'Get Started',
    'landing.hero.cta_subtitle': 'Secure authentication with Internet Identity',

    'landing.benefits.title': 'Why Choose AuditorBox?',
    'landing.benefits.subtitle': 'Built specifically for audit professionals with enterprise-grade security and compliance.',
    'landing.benefits.efficiency.title': 'Enhanced Efficiency',
    'landing.benefits.efficiency.description': 'Streamline your audit workflows with automated data processing, intelligent organization, and seamless collaboration tools.',
    'landing.benefits.security.title': 'Enterprise Security',
    'landing.benefits.security.description': 'Built on Internet Computer with Internet Identity authentication, ensuring the highest levels of security and data protection.',
    'landing.benefits.insights.title': 'Powerful Insights',
    'landing.benefits.insights.description': 'Advanced analytics and reporting capabilities help you make informed decisions and deliver better audit outcomes.',

    'landing.features.title': 'Comprehensive Audit Management',
    'landing.features.subtitle': 'Everything you need to manage your audit engagements from start to finish.',
    'landing.features.organizations.title': 'Organization Management',
    'landing.features.organizations.description': 'Create and manage audit organizations with comprehensive tracking and reporting capabilities.',
    'landing.features.organizations.highlight1': 'Multi-organization support',
    'landing.features.organizations.highlight2': 'Detailed organization profiles',
    'landing.features.organizations.highlight3': 'Activity tracking and audit trails',
    'landing.features.entities.title': 'Entity Management',
    'landing.features.entities.description': 'Manage entities within organizations with XBRL taxonomy support for compliance.',
    'landing.features.entities.highlight1': 'XBRL taxonomy assignment',
    'landing.features.entities.highlight2': 'US GAAP, IFRS, and other standards',
    'landing.features.entities.highlight3': 'Entity-specific configurations',
    'landing.features.engagements.title': 'Engagement Tracking',
    'landing.features.engagements.description': 'Track audit engagements with status management and progress monitoring.',
    'landing.features.engagements.highlight1': 'Status-based workflow management',
    'landing.features.engagements.highlight2': 'Date tracking and scheduling',
    'landing.features.engagements.highlight3': 'Organization and entity linking',
    'landing.features.data_import.title': 'Data Import & Analysis',
    'landing.features.data_import.description': 'Import Excel files with automatic data profiling and intelligent type detection.',
    'landing.features.data_import.highlight1': 'Multi-format Excel support',
    'landing.features.data_import.highlight2': 'Automatic PII detection',
    'landing.features.data_import.highlight3': 'Data quality analysis',
    'landing.features.documents.title': 'Document Management',
    'landing.features.documents.description': 'Secure document submission and management with role-based access control.',
    'landing.features.documents.highlight1': 'Multi-format document support',
    'landing.features.documents.highlight2': 'Secure storage and access',
    'landing.features.documents.highlight3': 'Audit trail and versioning',
    'landing.features.user_management.title': 'User Management',
    'landing.features.user_management.description': 'Advanced role-based access control with six distinct user roles.',
    'landing.features.user_management.highlight1': 'Six-tier role system',
    'landing.features.user_management.highlight2': 'Granular permissions',
    'landing.features.user_management.highlight3': 'User activity monitoring',

    'landing.how_it_works.title': 'How It Works',
    'landing.how_it_works.subtitle': 'Get started with AuditorBox in four simple steps.',
    'landing.how_it_works.step1.title': 'Secure Login',
    'landing.how_it_works.step1.description': 'Authenticate securely using Internet Identity for enterprise-grade security.',
    'landing.how_it_works.step2.title': 'Setup Organizations',
    'landing.how_it_works.step2.description': 'Create and configure your audit organizations and entities with XBRL taxonomies.',
    'landing.how_it_works.step3.title': 'Manage Engagements',
    'landing.how_it_works.step3.description': 'Track audit engagements with status management and progress monitoring.',
    'landing.how_it_works.step4.title': 'Analyze & Report',
    'landing.how_it_works.step4.description': 'Import data, manage documents, and generate comprehensive audit reports.',

    'landing.cta.title': 'Ready to Transform Your Audit Process?',
    'landing.cta.subtitle': 'Join audit professionals who trust AuditorBox for their engagement management needs.',
    'landing.cta.button': 'Start Your Journey',
    'landing.cta.note': 'No credit card required • Secure Internet Identity authentication',
    
    // Navigation
    'nav.core': 'Core',
    'nav.tools': 'Tools',
    'nav.admin': 'Admin',
    'nav.dashboard': 'Dashboard',
    'nav.dashboard_desc': 'Overview of your audit management system',
    'nav.organizations': 'Organizations',
    'nav.organizations_desc': 'Manage audit organizations and their information',
    'nav.entities': 'Entities',
    'nav.entities_desc': 'Manage entities with XBRL taxonomy assignments',
    'nav.engagements': 'Engagements',
    'nav.engagements_desc': 'Track audit engagements and their progress',
    'nav.workpapers': 'Working Papers',
    'nav.workpapers_desc': 'Automated working papers with financial analysis',
    'nav.activity': 'Activity Log',
    'nav.activity_desc': 'View system activity and audit trails',
    'nav.data_import': 'Data Import',
    'nav.data_import_desc': 'Import and analyze Excel files with data profiling',
    'nav.documents': 'Documents',
    'nav.documents_desc': 'Secure document submission and management',
    'nav.users': 'Users',
    'nav.users_desc': 'Manage user roles and permissions',
    
    // Authentication
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.logging_in': 'Logging in...',
    'auth.welcome': 'Welcome to AuditorBox',
    'auth.subtitle': 'Professional audit engagement management',
    'auth.get_started': 'Get Started',
    
    // Profile Setup
    'profile.setup_title': 'Complete Your Profile',
    'profile.setup_subtitle': 'Please provide your name to get started',
    'profile.name_label': 'Full Name',
    'profile.name_placeholder': 'Enter your full name',
    'profile.save': 'Save Profile',
    'profile.saving': 'Saving...',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back',
    'dashboard.overview': 'Overview of your audit management system',
    'dashboard.total_organizations': 'Total Organizations',
    'dashboard.total_entities': 'Total Entities',
    'dashboard.active_engagements': 'Active Engagements',
    'dashboard.total_engagements': 'Total Engagements',
    'dashboard.recent_activities': 'Recent Activities',
    'dashboard.recent_activity': 'Recent Activity',
    'dashboard.activity_description': 'Latest activities in your audit engagements',
    'dashboard.activity_badge': 'Activity',
    
    // Organizations
    'organizations.title': 'Organizations',
    'organizations.subtitle': 'Manage your audit organizations and their information',
    'organizations.add_new': 'Add New Organization',
    'organizations.all_organizations': 'All Organizations',
    'organizations.table_description': 'A list of all your organizations and their details',
    'organizations.name': 'Name',
    'organizations.description': 'Description',
    'organizations.created_at': 'Created',
    'organizations.actions': 'Actions',
    'organizations.edit': 'Edit',
    'organizations.view': 'View',
    'organizations.no_organizations': 'No organizations found',
    'organizations.create_first': 'Create your first organization to get started',
    
    // Organization Form
    'organization_form.create_title': 'Create New Organization',
    'organization_form.edit_title': 'Edit Organization',
    'organization_form.create_description': 'Enter the organization information to create a new organization',
    'organization_form.edit_description': 'Update the organization information below',
    'organization_form.name_label': 'Organization Name',
    'organization_form.name_placeholder': 'Enter organization name',
    'organization_form.description_label': 'Description',
    'organization_form.description_placeholder': 'Enter organization description',
    'organization_form.create': 'Create Organization',
    'organization_form.update': 'Update Organization',
    'organization_form.cancel': 'Cancel',
    'organization_form.creating': 'Creating...',
    'organization_form.updating': 'Updating...',
    
    // Entities
    'entities.title': 'Entities',
    'entities.subtitle': 'Manage entities within organizations and assign XBRL taxonomies',
    'entities.add_new': 'Add New Entity',
    'entities.all_entities': 'All Entities',
    'entities.table_description': 'A list of all entities with their assigned taxonomies',
    'entities.name': 'Name',
    'entities.organization': 'Organization',
    'entities.taxonomy': 'Taxonomy',
    'entities.description': 'Description',
    'entities.created_at': 'Created',
    'entities.actions': 'Actions',
    'entities.edit': 'Edit',
    'entities.view': 'View',
    'entities.no_entities': 'No entities found',
    'entities.create_first': 'Create your first entity to get started',
    
    // Entity Form
    'entity_form.create_title': 'Create New Entity',
    'entity_form.edit_title': 'Edit Entity',
    'entity_form.create_description': 'Enter the entity information and assign a taxonomy',
    'entity_form.edit_description': 'Update the entity information and taxonomy assignment',
    'entity_form.name_label': 'Entity Name',
    'entity_form.name_placeholder': 'Enter entity name',
    'entity_form.organization_label': 'Organization',
    'entity_form.organization_placeholder': 'Select an organization',
    'entity_form.taxonomy_label': 'XBRL Taxonomy',
    'entity_form.taxonomy_placeholder': 'Select a taxonomy',
    'entity_form.description_label': 'Description',
    'entity_form.description_placeholder': 'Enter entity description',
    'entity_form.create': 'Create Entity',
    'entity_form.update': 'Update Entity',
    'entity_form.cancel': 'Cancel',
    'entity_form.creating': 'Creating...',
    'entity_form.updating': 'Updating...',
    
    // Engagements
    'engagements.title': 'Engagements',
    'engagements.subtitle': 'Manage your audit engagements and track their progress',
    'engagements.add_new': 'Add New Engagement',
    'engagements.all_engagements': 'All Engagements',
    'engagements.table_description': 'A list of all your audit engagements and their current status',
    'engagements.name': 'Name',
    'engagements.organization': 'Organization',
    'engagements.entity': 'Entity',
    'engagements.status': 'Status',
    'engagements.start_date': 'Start Date',
    'engagements.end_date': 'End Date',
    'engagements.actions': 'Actions',
    'engagements.edit': 'Edit',
    'engagements.view': 'View',
    'engagements.no_engagements': 'No engagements found',
    'engagements.create_first': 'Create your first engagement to get started',
    
    // Engagement Form
    'engagement_form.create_title': 'Create New Engagement',
    'engagement_form.edit_title': 'Edit Engagement',
    'engagement_form.create_description': 'Enter the engagement information to create a new engagement',
    'engagement_form.edit_description': 'Update the engagement information below',
    'engagement_form.name_label': 'Engagement Name',
    'engagement_form.name_placeholder': 'Enter engagement name',
    'engagement_form.organization_label': 'Organization',
    'engagement_form.organization_placeholder': 'Select an organization',
    'engagement_form.entity_label': 'Entity',
    'engagement_form.entity_placeholder': 'Select an entity',
    'engagement_form.no_entities_message': 'No entities available for this organization. Please create an entity first.',
    'engagement_form.start_date_label': 'Start Date',
    'engagement_form.end_date_label': 'End Date',
    'engagement_form.status_label': 'Status',
    'engagement_form.status_placeholder': 'Select status',
    'engagement_form.create': 'Create Engagement',
    'engagement_form.update': 'Update Engagement',
    'engagement_form.cancel': 'Cancel',
    'engagement_form.creating': 'Creating...',
    'engagement_form.updating': 'Updating...',
    
    // Status options
    'status.planning': 'Planning',
    'status.in_progress': 'In Progress',
    'status.review': 'Review',
    'status.completed': 'Completed',
    'status.on_hold': 'On Hold',
    
    // Activity Log
    'activity.title': 'Activity Log',
    'activity.action': 'Action',
    'activity.user': 'User',
    'activity.timestamp': 'Timestamp',
    'activity.no_activity': 'No activity found',
    
    // Data Import
    'data_import.title': 'Data Import',
    'data_import.subtitle': 'Import and analyze Excel files with automatic data profiling',
    'data_import.upload_file': 'Upload Excel File',
    'data_import.upload_description': 'Select an Excel file (.xlsx or .xls) to import and analyze',
    'data_import.select_file': 'Select File',
    'data_import.processing': 'Processing file...',
    'data_import.uploading': 'Uploading file...',
    'data_import.sheet_selection': 'Sheet Selection',
    'data_import.schema_analysis': 'Schema Analysis',
    'data_import.columns_detected': 'columns detected',
    'data_import.column_name': 'Column Name',
    'data_import.data_type': 'Data Type',
    'data_import.unique': 'Unique',
    'data_import.null': 'Null',
    'data_import.samples': 'Samples',
    'data_import.data_preview': 'Data Preview',
    'data_import.preview_description': 'First 50 rows of your data with detected column types',
    'data_import.save_dataset': 'Save Dataset',
    'data_import.dataset_name': 'Dataset Name',
    'data_import.dataset_name_placeholder': 'Enter a name for this dataset',
    'data_import.save': 'Save Dataset',
    'data_import.saving': 'Saving...',
    'data_import.existing_datasets': 'Existing Datasets',
    'data_import.existing_datasets_description': 'Previously imported datasets',
    'data_import.no_datasets': 'No datasets imported yet',
    'data_import.name': 'Name',
    'data_import.version': 'Version',
    'data_import.columns': 'Columns',
    'data_import.created_at': 'Created At',
    'data_import.status': 'Status',
    'data_import.imported': 'Imported',
    
    // Working Papers
    'workpapers.title': 'Working Papers',
    'workpapers.subtitle': 'Automated working papers with financial analysis and calculations',
    'workpapers.add_new': 'Create Working Paper',
    'workpapers.all_papers': 'All Working Papers',
    'workpapers.table_description': 'Automated leadsheets with financial ratios, trend analysis, and variance analysis',
    'workpapers.name': 'Name',
    'workpapers.engagement': 'Engagement',
    'workpapers.organization': 'Organization',
    'workpapers.entity': 'Entity',
    'workpapers.accounts': 'Accounts',
    'workpapers.ratios': 'Ratios',
    'workpapers.created_at': 'Created',
    'workpapers.actions': 'Actions',
    'workpapers.edit': 'Edit',
    'workpapers.view': 'View',
    'workpapers.close': 'Close',
    'workpapers.no_papers': 'No working papers found',
    'workpapers.create_first': 'Create your first working paper to get started',
    'workpapers.total_papers': 'Total Papers',
    'workpapers.with_ratios': 'With Ratios',
    'workpapers.with_trends': 'With Trends',
    'workpapers.with_variance': 'With Variance',
    
    // Working Paper Form
    'workpapers.create_title': 'Create Working Paper',
    'workpapers.edit_title': 'Edit Working Paper',
    'workpapers.create_description': 'Create a new working paper with trial balance data and analysis',
    'workpapers.edit_description': 'Update the working paper information and data',
    'workpapers.name_label': 'Working Paper Name',
    'workpapers.name_placeholder': 'Enter working paper name',
    'workpapers.engagement_label': 'Engagement',
    'workpapers.engagement_placeholder': 'Select an engagement',
    'workpapers.description_label': 'Description',
    'workpapers.description_placeholder': 'Enter working paper description',
    'workpapers.trial_balance': 'Trial Balance',
    'workpapers.prior_period': 'Prior Period',
    'workpapers.expected_values': 'Expected Values',
    'workpapers.account_balances': 'Account Balances',
    'workpapers.account_balances_description': 'Enter the trial balance data for the current period',
    'workpapers.prior_period_data': 'Prior Period Data',
    'workpapers.prior_period_description': 'Enter the prior period balances for trend analysis',
    'workpapers.expected_values_description': 'Enter expected values for variance analysis',
    'workpapers.account_number': 'Account Number',
    'workpapers.account_name': 'Account Name',
    'workpapers.currency': 'Currency',
    'workpapers.opening_debit': 'Opening Debit',
    'workpapers.opening_credit': 'Opening Credit',
    'workpapers.period_debit': 'Period Debit',
    'workpapers.period_credit': 'Period Credit',
    'workpapers.ytd_debit': 'YTD Debit',
    'workpapers.ytd_credit': 'YTD Credit',
    'workpapers.entity_field': 'Entity',
    'workpapers.department': 'Department',
    'workpapers.project': 'Project',
    'workpapers.notes': 'Notes',
    'workpapers.expected_debit': 'Expected Debit',
    'workpapers.expected_credit': 'Expected Credit',
    'workpapers.add_account': 'Add Account',
    'workpapers.no_accounts': 'No accounts added yet',
    'workpapers.no_prior_data': 'No prior period data added yet',
    'workpapers.no_expected_values': 'No expected values added yet',
    'workpapers.create': 'Create Working Paper',
    'workpapers.update': 'Update Working Paper',
    'workpapers.cancel': 'Cancel',
    'workpapers.creating': 'Creating...',
    'workpapers.updating': 'Updating...',
    'workpapers.generate_with_analysis': 'Generate with Analysis',
    'workpapers.generating': 'Generating...',
    
    // Working Paper View
    'workpapers.paper_info': 'Working Paper Information',
    'workpapers.engagement_id': 'Engagement ID',
    'workpapers.updated_at': 'Updated At',
    'workpapers.supporting_docs': 'Supporting Documents',
    'workpapers.leadsheet': 'Leadsheet',
    'workpapers.leadsheet_description': 'Opening balances, adjustments, and closing balances for each account',
    'workpapers.financial_ratios': 'Financial Ratios',
    'workpapers.calculated_ratios': 'Calculated Financial Ratios',
    'workpapers.ratios_description': 'Automatically calculated financial ratios based on account balances',
    'workpapers.trend_analysis': 'Trend Analysis',
    'workpapers.trend_comparison': 'Trend Comparison',
    'workpapers.trend_description': 'Comparison between current and prior period balances',
    'workpapers.variance_analysis': 'Variance Analysis',
    'workpapers.variance_comparison': 'Variance Comparison',
    'workpapers.variance_description': 'Comparison between actual and expected values',
    'workpapers.supporting_documents': 'Supporting Documents',
    'workpapers.supporting_docs_description': 'Documents linked to this working paper for audit evidence',
    'workpapers.no_account_balances': 'No account balances available',
    'workpapers.no_ratios': 'No financial ratios calculated',
    'workpapers.no_trend_analysis': 'No trend analysis available',
    'workpapers.no_variance_analysis': 'No variance analysis available',
    'workpapers.current_period': 'Current Period',
    'workpapers.variance': 'Variance',
    'workpapers.percentage_change': '% Change',
    'workpapers.actual': 'Actual',
    'workpapers.expected': 'Expected',
    'workpapers.percentage_variance': '% Variance',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
  },
  ar: {
    // App
    'app.subtitle': 'إدارة التدقيق',
    
    // Landing Page
    'landing.hero.badge': 'إدارة التدقيق المهنية',
    'landing.hero.title': 'تبسيط مهام التدقيق الخاصة بك',
    'landing.hero.subtitle': 'منصة شاملة لإدارة مؤسسات التدقيق والكيانات والمهام والبيانات مع التحليلات المتقدمة والتعامل الآمن مع المستندات.',
    'landing.hero.cta_primary': 'ابدأ الآن',
    'landing.hero.cta_subtitle': 'مصادقة آمنة مع Internet Identity',

    'landing.benefits.title': 'لماذا تختار AuditorBox؟',
    'landing.benefits.subtitle': 'مصمم خصيصاً لمهنيي التدقيق مع أمان وامتثال على مستوى المؤسسات.',
    'landing.benefits.efficiency.title': 'كفاءة محسنة',
    'landing.benefits.efficiency.description': 'تبسيط سير عمل التدقيق مع معالجة البيانات الآلية والتنظيم الذكي وأدوات التعاون السلسة.',
    'landing.benefits.security.title': 'أمان المؤسسات',
    'landing.benefits.security.description': 'مبني على Internet Computer مع مصادقة Internet Identity، مما يضمن أعلى مستويات الأمان وحماية البيانات.',
    'landing.benefits.insights.title': 'رؤى قوية',
    'landing.benefits.insights.description': 'قدرات التحليلات والتقارير المتقدمة تساعدك على اتخاذ قرارات مدروسة وتقديم نتائج تدقيق أفضل.',

    'landing.features.title': 'إدارة تدقيق شاملة',
    'landing.features.subtitle': 'كل ما تحتاجه لإدارة مهام التدقيق من البداية إلى النهاية.',
    'landing.features.organizations.title': 'إدارة المؤسسات',
    'landing.features.organizations.description': 'إنشاء وإدارة مؤسسات التدقيق مع قدرات التتبع والتقارير الشاملة.',
    'landing.features.organizations.highlight1': 'دعم متعدد المؤسسات',
    'landing.features.organizations.highlight2': 'ملفات تعريف مفصلة للمؤسسات',
    'landing.features.organizations.highlight3': 'تتبع النشاط ومسارات التدقيق',
    'landing.features.entities.title': 'إدارة الكيانات',
    'landing.features.entities.description': 'إدارة الكيانات داخل المؤسسات مع دعم تصنيف XBRL للامتثال.',
    'landing.features.entities.highlight1': 'تعيين تصنيف XBRL',
    'landing.features.entities.highlight2': 'US GAAP و IFRS ومعايير أخرى',
    'landing.features.entities.highlight3': 'تكوينات خاصة بالكيان',
    'landing.features.engagements.title': 'تتبع المهام',
    'landing.features.engagements.description': 'تتبع مهام التدقيق مع إدارة الحالة ومراقبة التقدم.',
    'landing.features.engagements.highlight1': 'إدارة سير العمل القائمة على الحالة',
    'landing.features.engagements.highlight2': 'تتبع التواريخ والجدولة',
    'landing.features.engagements.highlight3': 'ربط المؤسسات والكيانات',
    'landing.features.data_import.title': 'استيراد وتحليل البيانات',
    'landing.features.data_import.description': 'استيراد ملفات Excel مع التحليل التلقائي للبيانات والكشف الذكي عن الأنواع.',
    'landing.features.data_import.highlight1': 'دعم متعدد الصيغ لـ Excel',
    'landing.features.data_import.highlight2': 'كشف تلقائي للمعلومات الشخصية',
    'landing.features.data_import.highlight3': 'تحليل جودة البيانات',
    'landing.features.documents.title': 'إدارة المستندات',
    'landing.features.documents.description': 'تقديم وإدارة آمنة للمستندات مع التحكم في الوصول القائم على الأدوار.',
    'landing.features.documents.highlight1': 'دعم متعدد الصيغ للمستندات',
    'landing.features.documents.highlight2': 'تخزين ووصول آمن',
    'landing.features.documents.highlight3': 'مسار التدقيق والإصدارات',
    'landing.features.user_management.title': 'إدارة المستخدمين',
    'landing.features.user_management.description': 'التحكم المتقدم في الوصول القائم على الأدوار مع ستة أدوار مستخدم متميزة.',
    'landing.features.user_management.highlight1': 'نظام أدوار من ستة مستويات',
    'landing.features.user_management.highlight2': 'صلاحيات مفصلة',
    'landing.features.user_management.highlight3': 'مراقبة نشاط المستخدم',

    'landing.how_it_works.title': 'كيف يعمل',
    'landing.how_it_works.subtitle': 'ابدأ مع AuditorBox في أربع خطوات بسيطة.',
    'landing.how_it_works.step1.title': 'تسجيل دخول آمن',
    'landing.how_it_works.step1.description': 'المصادقة الآمنة باستخدام Internet Identity للحصول على أمان على مستوى المؤسسات.',
    'landing.how_it_works.step2.title': 'إعداد المؤسسات',
    'landing.how_it_works.step2.description': 'إنشاء وتكوين مؤسسات التدقيق والكيانات مع تصنيفات XBRL.',
    'landing.how_it_works.step3.title': 'إدارة المهام',
    'landing.how_it_works.step3.description': 'تتبع مهام التدقيق مع إدارة الحالة ومراقبة التقدم.',
    'landing.how_it_works.step4.title': 'تحليل وتقرير',
    'landing.how_it_works.step4.description': 'استيراد البيانات وإدارة المستندات وإنشاء تقارير تدقيق شاملة.',

    'landing.cta.title': 'مستعد لتحويل عملية التدقيق الخاصة بك؟',
    'landing.cta.subtitle': 'انضم إلى مهنيي التدقيق الذين يثقون في AuditorBox لاحتياجات إدارة المهام.',
    'landing.cta.button': 'ابدأ رحلتك',
    'landing.cta.note': 'لا حاجة لبطاقة ائتمان • مصادقة Internet Identity آمنة',
    
    // Navigation
    'nav.core': 'الأساسي',
    'nav.tools': 'الأدوات',
    'nav.admin': 'الإدارة',
    'nav.dashboard': 'لوحة التحكم',
    'nav.dashboard_desc': 'نظرة عامة على نظام إدارة التدقيق',
    'nav.organizations': 'المؤسسات',
    'nav.organizations_desc': 'إدارة مؤسسات التدقيق ومعلوماتها',
    'nav.entities': 'الكيانات',
    'nav.entities_desc': 'إدارة الكيانات مع تعيينات تصنيف XBRL',
    'nav.engagements': 'المهام',
    'nav.engagements_desc': 'تتبع مهام التدقيق وتقدمها',
    'nav.workpapers': 'أوراق العمل',
    'nav.workpapers_desc': 'أوراق عمل آلية مع التحليل المالي',
    'nav.activity': 'سجل النشاط',
    'nav.activity_desc': 'عرض نشاط النظام ومسارات التدقيق',
    'nav.data_import': 'استيراد البيانات',
    'nav.data_import_desc': 'استيراد وتحليل ملفات Excel مع تحليل البيانات',
    'nav.documents': 'المستندات',
    'nav.documents_desc': 'تقديم وإدارة آمنة للمستندات',
    'nav.users': 'المستخدمون',
    'nav.users_desc': 'إدارة أدوار وصلاحيات المستخدمين',
    
    // Authentication
    'auth.login': 'تسجيل الدخول',
    'auth.logout': 'تسجيل الخروج',
    'auth.logging_in': 'جاري تسجيل الدخول...',
    'auth.welcome': 'مرحباً بك في AuditorBox',
    'auth.subtitle': 'إدارة مهام التدقيق المهنية',
    'auth.get_started': 'ابدأ الآن',
    
    // Profile Setup
    'profile.setup_title': 'أكمل ملفك الشخصي',
    'profile.setup_subtitle': 'يرجى تقديم اسمك للبدء',
    'profile.name_label': 'الاسم الكامل',
    'profile.name_placeholder': 'أدخل اسمك الكامل',
    'profile.save': 'حفظ الملف الشخصي',
    'profile.saving': 'جاري الحفظ...',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.welcome': 'مرحباً بعودتك',
    'dashboard.overview': 'نظرة عامة على نظام إدارة التدقيق',
    'dashboard.total_organizations': 'إجمالي المؤسسات',
    'dashboard.total_entities': 'إجمالي الكيانات',
    'dashboard.active_engagements': 'المهام النشطة',
    'dashboard.total_engagements': 'إجمالي المهام',
    'dashboard.recent_activities': 'الأنشطة الأخيرة',
    'dashboard.recent_activity': 'النشاط الأخير',
    'dashboard.activity_description': 'آخر الأنشطة في مهام التدقيق',
    'dashboard.activity_badge': 'نشاط',
    
    // Organizations
    'organizations.title': 'المؤسسات',
    'organizations.subtitle': 'إدارة مؤسسات التدقيق ومعلوماتها',
    'organizations.add_new': 'إضافة مؤسسة جديدة',
    'organizations.all_organizations': 'جميع المؤسسات',
    'organizations.table_description': 'قائمة بجميع مؤسساتك وتفاصيلها',
    'organizations.name': 'الاسم',
    'organizations.description': 'الوصف',
    'organizations.created_at': 'تاريخ الإنشاء',
    'organizations.actions': 'الإجراءات',
    'organizations.edit': 'تعديل',
    'organizations.view': 'عرض',
    'organizations.no_organizations': 'لا توجد مؤسسات',
    'organizations.create_first': 'أنشئ مؤسستك الأولى للبدء',
    
    // Organization Form
    'organization_form.create_title': 'إنشاء مؤسسة جديدة',
    'organization_form.edit_title': 'تعديل المؤسسة',
    'organization_form.create_description': 'أدخل معلومات المؤسسة لإنشاء مؤسسة جديدة',
    'organization_form.edit_description': 'تحديث معلومات المؤسسة أدناه',
    'organization_form.name_label': 'اسم المؤسسة',
    'organization_form.name_placeholder': 'أدخل اسم المؤسسة',
    'organization_form.description_label': 'الوصف',
    'organization_form.description_placeholder': 'أدخل وصف المؤسسة',
    'organization_form.create': 'إنشاء المؤسسة',
    'organization_form.update': 'تحديث المؤسسة',
    'organization_form.cancel': 'إلغاء',
    'organization_form.creating': 'جاري الإنشاء...',
    'organization_form.updating': 'جاري التحديث...',
    
    // Entities
    'entities.title': 'الكيانات',
    'entities.subtitle': 'إدارة الكيانات داخل المؤسسات وتعيين تصنيفات XBRL',
    'entities.add_new': 'إضافة كيان جديد',
    'entities.all_entities': 'جميع الكيانات',
    'entities.table_description': 'قائمة بجميع الكيانات مع تصنيفاتها المعينة',
    'entities.name': 'الاسم',
    'entities.organization': 'المؤسسة',
    'entities.taxonomy': 'التصنيف',
    'entities.description': 'الوصف',
    'entities.created_at': 'تاريخ الإنشاء',
    'entities.actions': 'الإجراءات',
    'entities.edit': 'تعديل',
    'entities.view': 'عرض',
    'entities.no_entities': 'لا توجد كيانات',
    'entities.create_first': 'أنشئ كيانك الأول للبدء',
    
    // Entity Form
    'entity_form.create_title': 'إنشاء كيان جديد',
    'entity_form.edit_title': 'تعديل الكيان',
    'entity_form.create_description': 'أدخل معلومات الكيان وعين تصنيفاً',
    'entity_form.edit_description': 'تحديث معلومات الكيان وتعيين التصنيف',
    'entity_form.name_label': 'اسم الكيان',
    'entity_form.name_placeholder': 'أدخل اسم الكيان',
    'entity_form.organization_label': 'المؤسسة',
    'entity_form.organization_placeholder': 'اختر مؤسسة',
    'entity_form.taxonomy_label': 'تصنيف XBRL',
    'entity_form.taxonomy_placeholder': 'اختر تصنيفاً',
    'entity_form.description_label': 'الوصف',
    'entity_form.description_placeholder': 'أدخل وصف الكيان',
    'entity_form.create': 'إنشاء الكيان',
    'entity_form.update': 'تحديث الكيان',
    'entity_form.cancel': 'إلغاء',
    'entity_form.creating': 'جاري الإنشاء...',
    'entity_form.updating': 'جاري التحديث...',
    
    // Engagements
    'engagements.title': 'المهام',
    'engagements.subtitle': 'إدارة مهام التدقيق وتتبع تقدمها',
    'engagements.add_new': 'إضافة مهمة جديدة',
    'engagements.all_engagements': 'جميع المهام',
    'engagements.table_description': 'قائمة بجميع مهام التدقيق وحالتها الحالية',
    'engagements.name': 'الاسم',
    'engagements.organization': 'المؤسسة',
    'engagements.entity': 'الكيان',
    'engagements.status': 'الحالة',
    'engagements.start_date': 'تاريخ البداية',
    'engagements.end_date': 'تاريخ النهاية',
    'engagements.actions': 'الإجراءات',
    'engagements.edit': 'تعديل',
    'engagements.view': 'عرض',
    'engagements.no_engagements': 'لا توجد مهام',
    'engagements.create_first': 'أنشئ مهمتك الأولى للبدء',
    
    // Engagement Form
    'engagement_form.create_title': 'إنشاء مهمة جديدة',
    'engagement_form.edit_title': 'تعديل المهمة',
    'engagement_form.create_description': 'أدخل معلومات المهمة لإنشاء مهمة جديدة',
    'engagement_form.edit_description': 'تحديث معلومات المهمة أدناه',
    'engagement_form.name_label': 'اسم المهمة',
    'engagement_form.name_placeholder': 'أدخل اسم المهمة',
    'engagement_form.organization_label': 'المؤسسة',
    'engagement_form.organization_placeholder': 'اختر مؤسسة',
    'engagement_form.entity_label': 'الكيان',
    'engagement_form.entity_placeholder': 'اختر كياناً',
    'engagement_form.no_entities_message': 'لا توجد كيانات متاحة لهذه المؤسسة. يرجى إنشاء كيان أولاً.',
    'engagement_form.start_date_label': 'تاريخ البداية',
    'engagement_form.end_date_label': 'تاريخ النهاية',
    'engagement_form.status_label': 'الحالة',
    'engagement_form.status_placeholder': 'اختر الحالة',
    'engagement_form.create': 'إنشاء المهمة',
    'engagement_form.update': 'تحديث المهمة',
    'engagement_form.cancel': 'إلغاء',
    'engagement_form.creating': 'جاري الإنشاء...',
    'engagement_form.updating': 'جاري التحديث...',
    
    // Status options
    'status.planning': 'التخطيط',
    'status.in_progress': 'قيد التنفيذ',
    'status.review': 'المراجعة',
    'status.completed': 'مكتمل',
    'status.on_hold': 'معلق',
    
    // Activity Log
    'activity.title': 'سجل النشاط',
    'activity.action': 'الإجراء',
    'activity.user': 'المستخدم',
    'activity.timestamp': 'الوقت',
    'activity.no_activity': 'لا يوجد نشاط',
    
    // Data Import
    'data_import.title': 'استيراد البيانات',
    'data_import.subtitle': 'استيراد وتحليل ملفات Excel مع التحليل التلقائي للبيانات',
    'data_import.upload_file': 'رفع ملف Excel',
    'data_import.upload_description': 'اختر ملف Excel (.xlsx أو .xls) للاستيراد والتحليل',
    'data_import.select_file': 'اختر ملف',
    'data_import.processing': 'جاري معالجة الملف...',
    'data_import.uploading': 'جاري رفع الملف...',
    'data_import.sheet_selection': 'اختيار الورقة',
    'data_import.schema_analysis': 'تحليل المخطط',
    'data_import.columns_detected': 'عمود تم اكتشافه',
    'data_import.column_name': 'اسم العمود',
    'data_import.data_type': 'نوع البيانات',
    'data_import.unique': 'فريد',
    'data_import.null': 'فارغ',
    'data_import.samples': 'عينات',
    'data_import.data_preview': 'معاينة البيانات',
    'data_import.preview_description': 'أول 50 صف من بياناتك مع أنواع الأعمدة المكتشفة',
    'data_import.save_dataset': 'حفظ مجموعة البيانات',
    'data_import.dataset_name': 'اسم مجموعة البيانات',
    'data_import.dataset_name_placeholder': 'أدخل اسماً لمجموعة البيانات هذه',
    'data_import.save': 'حفظ مجموعة البيانات',
    'data_import.saving': 'جاري الحفظ...',
    'data_import.existing_datasets': 'مجموعات البيانات الموجودة',
    'data_import.existing_datasets_description': 'مجموعات البيانات المستوردة سابقاً',
    'data_import.no_datasets': 'لم يتم استيراد أي مجموعة بيانات بعد',
    'data_import.name': 'الاسم',
    'data_import.version': 'الإصدار',
    'data_import.columns': 'الأعمدة',
    'data_import.created_at': 'تاريخ الإنشاء',
    'data_import.status': 'الحالة',
    'data_import.imported': 'مستورد',
    
    // Working Papers
    'workpapers.title': 'أوراق العمل',
    'workpapers.subtitle': 'أوراق عمل آلية مع التحليل المالي والحسابات',
    'workpapers.add_new': 'إنشاء ورقة عمل',
    'workpapers.all_papers': 'جميع أوراق العمل',
    'workpapers.table_description': 'كشوف حسابات آلية مع النسب المالية وتحليل الاتجاهات وتحليل التباين',
    'workpapers.name': 'الاسم',
    'workpapers.engagement': 'المهمة',
    'workpapers.organization': 'المؤسسة',
    'workpapers.entity': 'الكيان',
    'workpapers.accounts': 'الحسابات',
    'workpapers.ratios': 'النسب',
    'workpapers.created_at': 'تاريخ الإنشاء',
    'workpapers.actions': 'الإجراءات',
    'workpapers.edit': 'تعديل',
    'workpapers.view': 'عرض',
    'workpapers.close': 'إغلاق',
    'workpapers.no_papers': 'لا توجد أوراق عمل',
    'workpapers.create_first': 'أنشئ ورقة العمل الأولى للبدء',
    'workpapers.total_papers': 'إجمالي الأوراق',
    'workpapers.with_ratios': 'مع النسب',
    'workpapers.with_trends': 'مع الاتجاهات',
    'workpapers.with_variance': 'مع التباين',
    
    // Working Paper Form
    'workpapers.create_title': 'إنشاء ورقة عمل',
    'workpapers.edit_title': 'تعديل ورقة العمل',
    'workpapers.create_description': 'إنشاء ورقة عمل جديدة مع بيانات ميزان المراجعة والتحليل',
    'workpapers.edit_description': 'تحديث معلومات ورقة العمل والبيانات',
    'workpapers.name_label': 'اسم ورقة العمل',
    'workpapers.name_placeholder': 'أدخل اسم ورقة العمل',
    'workpapers.engagement_label': 'المهمة',
    'workpapers.engagement_placeholder': 'اختر مهمة',
    'workpapers.description_label': 'الوصف',
    'workpapers.description_placeholder': 'أدخل وصف ورقة العمل',
    'workpapers.trial_balance': 'ميزان المراجعة',
    'workpapers.prior_period': 'الفترة السابقة',
    'workpapers.expected_values': 'القيم المتوقعة',
    'workpapers.account_balances': 'أرصدة الحسابات',
    'workpapers.account_balances_description': 'أدخل بيانات ميزان المراجعة للفترة الحالية',
    'workpapers.prior_period_data': 'بيانات الفترة السابقة',
    'workpapers.prior_period_description': 'أدخل أرصدة الفترة السابقة لتحليل الاتجاهات',
    'workpapers.expected_values_description': 'أدخل القيم المتوقعة لتحليل التباين',
    'workpapers.account_number': 'رقم الحساب',
    'workpapers.account_name': 'اسم الحساب',
    'workpapers.currency': 'العملة',
    'workpapers.opening_debit': 'الرصيد الافتتاحي مدين',
    'workpapers.opening_credit': 'الرصيد الافتتاحي دائن',
    'workpapers.period_debit': 'حركة الفترة مدين',
    'workpapers.period_credit': 'حركة الفترة دائن',
    'workpapers.ytd_debit': 'إجمالي السنة مدين',
    'workpapers.ytd_credit': 'إجمالي السنة دائن',
    'workpapers.entity_field': 'الكيان',
    'workpapers.department': 'القسم',
    'workpapers.project': 'المشروع',
    'workpapers.notes': 'الملاحظات',
    'workpapers.expected_debit': 'المتوقع مدين',
    'workpapers.expected_credit': 'المتوقع دائن',
    'workpapers.add_account': 'إضافة حساب',
    'workpapers.no_accounts': 'لم يتم إضافة حسابات بعد',
    'workpapers.no_prior_data': 'لم يتم إضافة بيانات الفترة السابقة بعد',
    'workpapers.no_expected_values': 'لم يتم إضافة القيم المتوقعة بعد',
    'workpapers.create': 'إنشاء ورقة العمل',
    'workpapers.update': 'تحديث ورقة العمل',
    'workpapers.cancel': 'إلغاء',
    'workpapers.creating': 'جاري الإنشاء...',
    'workpapers.updating': 'جاري التحديث...',
    'workpapers.generate_with_analysis': 'إنشاء مع التحليل',
    'workpapers.generating': 'جاري الإنشاء...',
    
    // Working Paper View
    'workpapers.paper_info': 'معلومات ورقة العمل',
    'workpapers.engagement_id': 'رقم المهمة',
    'workpapers.updated_at': 'تاريخ التحديث',
    'workpapers.supporting_docs': 'المستندات المساندة',
    'workpapers.leadsheet': 'كشف الحساب',
    'workpapers.leadsheet_description': 'الأرصدة الافتتاحية والتسويات والأرصدة الختامية لكل حساب',
    'workpapers.financial_ratios': 'النسب المالية',
    'workpapers.calculated_ratios': 'النسب المالية المحسوبة',
    'workpapers.ratios_description': 'النسب المالية المحسوبة تلقائياً بناءً على أرصدة الحسابات',
    'workpapers.trend_analysis': 'تحليل الاتجاهات',
    'workpapers.trend_comparison': 'مقارنة الاتجاهات',
    'workpapers.trend_description': 'مقارنة بين أرصدة الفترة الحالية والسابقة',
    'workpapers.variance_analysis': 'تحليل التباين',
    'workpapers.variance_comparison': 'مقارنة التباين',
    'workpapers.variance_description': 'مقارنة بين القيم الفعلية والمتوقعة',
    'workpapers.supporting_documents': 'المستندات المساندة',
    'workpapers.supporting_docs_description': 'المستندات المرتبطة بورقة العمل هذه كأدلة تدقيق',
    'workpapers.no_account_balances': 'لا توجد أرصدة حسابات متاحة',
    'workpapers.no_ratios': 'لم يتم حساب نسب مالية',
    'workpapers.no_trend_analysis': 'لا يوجد تحليل اتجاهات متاح',
    'workpapers.no_variance_analysis': 'لا يوجد تحليل تباين متاح',
    'workpapers.current_period': 'الفترة الحالية',
    'workpapers.variance': 'التباين',
    'workpapers.percentage_change': '% التغيير',
    'workpapers.actual': 'الفعلي',
    'workpapers.expected': 'المتوقع',
    'workpapers.percentage_variance': '% التباين',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.view': 'عرض',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { identity } = useInternetIdentity();
  const { data: languagePreference } = useGetLanguagePreference();
  const { mutate: setLanguagePreference } = useSetLanguagePreference();
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    if (languagePreference?.language) {
      setLanguageState(languagePreference.language as Language);
    }
  }, [languagePreference]);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (identity) {
      setLanguagePreference(lang);
    }
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
